# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steammessages_offline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import steam.protobufs.steammessages_unified_base_pb2 as steammessages__unified__base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='steammessages_offline.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\220\001\001'),
  serialized_pb=_b('\n\x1bsteammessages_offline.proto\x1a steammessages_unified_base.proto\":\n&COffline_GetOfflineLogonTicket_Request\x12\x10\n\x08priority\x18\x01 \x01(\r\"W\n\'COffline_GetOfflineLogonTicket_Response\x12\x19\n\x11serialized_ticket\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"0\n.COffline_GetUnsignedOfflineLogonTicket_Request\"O\n\x1b\x43Offline_OfflineLogonTicket\x12\x11\n\taccountid\x18\x01 \x01(\r\x12\x1d\n\x15rtime32_creation_time\x18\x02 \x01(\x07\"_\n/COffline_GetUnsignedOfflineLogonTicket_Response\x12,\n\x06ticket\x18\x01 \x01(\x0b\x32\x1c.COffline_OfflineLogonTicket2\xa3\x03\n\x07Offline\x12\xb5\x01\n\x15GetOfflineLogonTicket\x12\'.COffline_GetOfflineLogonTicket_Request\x1a(.COffline_GetOfflineLogonTicket_Response\"I\x82\xb5\x18\x45Get a serialized and signed offline logon ticket for the current user\x12\xc1\x01\n\x1dGetUnsignedOfflineLogonTicket\x12/.COffline_GetUnsignedOfflineLogonTicket_Request\x1a\x30.COffline_GetUnsignedOfflineLogonTicket_Response\"=\x82\xb5\x18\x39Get an unsigned offline logon ticket for the current user\x1a\x1c\x82\xb5\x18\x18Offline settings serviceB\x03\x90\x01\x01')
  ,
  dependencies=[steammessages__unified__base__pb2.DESCRIPTOR,])




_COFFLINE_GETOFFLINELOGONTICKET_REQUEST = _descriptor.Descriptor(
  name='COffline_GetOfflineLogonTicket_Request',
  full_name='COffline_GetOfflineLogonTicket_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='priority', full_name='COffline_GetOfflineLogonTicket_Request.priority', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=123,
)


_COFFLINE_GETOFFLINELOGONTICKET_RESPONSE = _descriptor.Descriptor(
  name='COffline_GetOfflineLogonTicket_Response',
  full_name='COffline_GetOfflineLogonTicket_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serialized_ticket', full_name='COffline_GetOfflineLogonTicket_Response.serialized_ticket', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='COffline_GetOfflineLogonTicket_Response.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=212,
)


_COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_REQUEST = _descriptor.Descriptor(
  name='COffline_GetUnsignedOfflineLogonTicket_Request',
  full_name='COffline_GetUnsignedOfflineLogonTicket_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=262,
)


_COFFLINE_OFFLINELOGONTICKET = _descriptor.Descriptor(
  name='COffline_OfflineLogonTicket',
  full_name='COffline_OfflineLogonTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountid', full_name='COffline_OfflineLogonTicket.accountid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rtime32_creation_time', full_name='COffline_OfflineLogonTicket.rtime32_creation_time', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=343,
)


_COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_RESPONSE = _descriptor.Descriptor(
  name='COffline_GetUnsignedOfflineLogonTicket_Response',
  full_name='COffline_GetUnsignedOfflineLogonTicket_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket', full_name='COffline_GetUnsignedOfflineLogonTicket_Response.ticket', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=440,
)

_COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_RESPONSE.fields_by_name['ticket'].message_type = _COFFLINE_OFFLINELOGONTICKET
DESCRIPTOR.message_types_by_name['COffline_GetOfflineLogonTicket_Request'] = _COFFLINE_GETOFFLINELOGONTICKET_REQUEST
DESCRIPTOR.message_types_by_name['COffline_GetOfflineLogonTicket_Response'] = _COFFLINE_GETOFFLINELOGONTICKET_RESPONSE
DESCRIPTOR.message_types_by_name['COffline_GetUnsignedOfflineLogonTicket_Request'] = _COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_REQUEST
DESCRIPTOR.message_types_by_name['COffline_OfflineLogonTicket'] = _COFFLINE_OFFLINELOGONTICKET
DESCRIPTOR.message_types_by_name['COffline_GetUnsignedOfflineLogonTicket_Response'] = _COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

COffline_GetOfflineLogonTicket_Request = _reflection.GeneratedProtocolMessageType('COffline_GetOfflineLogonTicket_Request', (_message.Message,), dict(
  DESCRIPTOR = _COFFLINE_GETOFFLINELOGONTICKET_REQUEST,
  __module__ = 'steammessages_offline_pb2'
  # @@protoc_insertion_point(class_scope:COffline_GetOfflineLogonTicket_Request)
  ))
_sym_db.RegisterMessage(COffline_GetOfflineLogonTicket_Request)

COffline_GetOfflineLogonTicket_Response = _reflection.GeneratedProtocolMessageType('COffline_GetOfflineLogonTicket_Response', (_message.Message,), dict(
  DESCRIPTOR = _COFFLINE_GETOFFLINELOGONTICKET_RESPONSE,
  __module__ = 'steammessages_offline_pb2'
  # @@protoc_insertion_point(class_scope:COffline_GetOfflineLogonTicket_Response)
  ))
_sym_db.RegisterMessage(COffline_GetOfflineLogonTicket_Response)

COffline_GetUnsignedOfflineLogonTicket_Request = _reflection.GeneratedProtocolMessageType('COffline_GetUnsignedOfflineLogonTicket_Request', (_message.Message,), dict(
  DESCRIPTOR = _COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_REQUEST,
  __module__ = 'steammessages_offline_pb2'
  # @@protoc_insertion_point(class_scope:COffline_GetUnsignedOfflineLogonTicket_Request)
  ))
_sym_db.RegisterMessage(COffline_GetUnsignedOfflineLogonTicket_Request)

COffline_OfflineLogonTicket = _reflection.GeneratedProtocolMessageType('COffline_OfflineLogonTicket', (_message.Message,), dict(
  DESCRIPTOR = _COFFLINE_OFFLINELOGONTICKET,
  __module__ = 'steammessages_offline_pb2'
  # @@protoc_insertion_point(class_scope:COffline_OfflineLogonTicket)
  ))
_sym_db.RegisterMessage(COffline_OfflineLogonTicket)

COffline_GetUnsignedOfflineLogonTicket_Response = _reflection.GeneratedProtocolMessageType('COffline_GetUnsignedOfflineLogonTicket_Response', (_message.Message,), dict(
  DESCRIPTOR = _COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_RESPONSE,
  __module__ = 'steammessages_offline_pb2'
  # @@protoc_insertion_point(class_scope:COffline_GetUnsignedOfflineLogonTicket_Response)
  ))
_sym_db.RegisterMessage(COffline_GetUnsignedOfflineLogonTicket_Response)


DESCRIPTOR._options = None

_OFFLINE = _descriptor.ServiceDescriptor(
  name='Offline',
  full_name='Offline',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\202\265\030\030Offline settings service'),
  serialized_start=443,
  serialized_end=862,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOfflineLogonTicket',
    full_name='Offline.GetOfflineLogonTicket',
    index=0,
    containing_service=None,
    input_type=_COFFLINE_GETOFFLINELOGONTICKET_REQUEST,
    output_type=_COFFLINE_GETOFFLINELOGONTICKET_RESPONSE,
    serialized_options=_b('\202\265\030EGet a serialized and signed offline logon ticket for the current user'),
  ),
  _descriptor.MethodDescriptor(
    name='GetUnsignedOfflineLogonTicket',
    full_name='Offline.GetUnsignedOfflineLogonTicket',
    index=1,
    containing_service=None,
    input_type=_COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_REQUEST,
    output_type=_COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_RESPONSE,
    serialized_options=_b('\202\265\0309Get an unsigned offline logon ticket for the current user'),
  ),
])
_sym_db.RegisterServiceDescriptor(_OFFLINE)

DESCRIPTOR.services_by_name['Offline'] = _OFFLINE

Offline = service_reflection.GeneratedServiceType('Offline', (_service.Service,), dict(
  DESCRIPTOR = _OFFLINE,
  __module__ = 'steammessages_offline_pb2'
  ))

Offline_Stub = service_reflection.GeneratedServiceStubType('Offline_Stub', (Offline,), dict(
  DESCRIPTOR = _OFFLINE,
  __module__ = 'steammessages_offline_pb2'
  ))


# @@protoc_insertion_point(module_scope)
