# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from abc import (
    ABCMeta as abc___ABCMeta,
    abstractmethod as abc___abstractmethod,
)

from concurrent.futures import (
    Future as concurrent___futures___Future,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.service import (
    RpcChannel as google___protobuf___service___RpcChannel,
    RpcController as google___protobuf___service___RpcController,
    Service as google___protobuf___service___Service,
)

from steammessages_unified_base_pb2 import (
    NoResponse as steammessages_unified_base_pb2___NoResponse,
)

from typing import (
    Callable as typing___Callable,
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

EUserReviewScorePreferenceValue = typing___NewType('EUserReviewScorePreferenceValue', builtin___int)
type___EUserReviewScorePreferenceValue = EUserReviewScorePreferenceValue
EUserReviewScorePreference: _EUserReviewScorePreference
class _EUserReviewScorePreference(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[EUserReviewScorePreferenceValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    k_EUserReviewScorePreference_Unset = typing___cast(EUserReviewScorePreferenceValue, 0)
    k_EUserReviewScorePreference_IncludeAll = typing___cast(EUserReviewScorePreferenceValue, 1)
    k_EUserReviewScorePreference_ExcludeBombs = typing___cast(EUserReviewScorePreferenceValue, 2)
k_EUserReviewScorePreference_Unset = typing___cast(EUserReviewScorePreferenceValue, 0)
k_EUserReviewScorePreference_IncludeAll = typing___cast(EUserReviewScorePreferenceValue, 1)
k_EUserReviewScorePreference_ExcludeBombs = typing___cast(EUserReviewScorePreferenceValue, 2)
type___EUserReviewScorePreference = EUserReviewScorePreference

class CStore_GetLocalizedNameForTags_Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    language: typing___Text = ...
    tagids: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        language : typing___Optional[typing___Text] = None,
        tagids : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"language",b"language"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"language",b"language",u"tagids",b"tagids"]) -> None: ...
type___CStore_GetLocalizedNameForTags_Request = CStore_GetLocalizedNameForTags_Request

class CStore_GetLocalizedNameForTags_Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Tag(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        tagid: builtin___int = ...
        english_name: typing___Text = ...
        name: typing___Text = ...

        def __init__(self,
            *,
            tagid : typing___Optional[builtin___int] = None,
            english_name : typing___Optional[typing___Text] = None,
            name : typing___Optional[typing___Text] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"english_name",b"english_name",u"name",b"name",u"tagid",b"tagid"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"english_name",b"english_name",u"name",b"name",u"tagid",b"tagid"]) -> None: ...
    type___Tag = Tag


    @property
    def tags(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___CStore_GetLocalizedNameForTags_Response.Tag]: ...

    def __init__(self,
        *,
        tags : typing___Optional[typing___Iterable[type___CStore_GetLocalizedNameForTags_Response.Tag]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"tags",b"tags"]) -> None: ...
type___CStore_GetLocalizedNameForTags_Response = CStore_GetLocalizedNameForTags_Response

class CStore_GetStorePreferences_Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___CStore_GetStorePreferences_Request = CStore_GetStorePreferences_Request

class CStore_UserPreferences(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    primary_language: builtin___int = ...
    secondary_languages: builtin___int = ...
    platform_windows: builtin___bool = ...
    platform_mac: builtin___bool = ...
    platform_linux: builtin___bool = ...
    hide_adult_content_violence: builtin___bool = ...
    hide_adult_content_sex: builtin___bool = ...
    timestamp_updated: builtin___int = ...
    hide_store_broadcast: builtin___bool = ...
    review_score_preference: type___EUserReviewScorePreferenceValue = ...
    timestamp_content_descriptor_preferences_updated: builtin___int = ...

    def __init__(self,
        *,
        primary_language : typing___Optional[builtin___int] = None,
        secondary_languages : typing___Optional[builtin___int] = None,
        platform_windows : typing___Optional[builtin___bool] = None,
        platform_mac : typing___Optional[builtin___bool] = None,
        platform_linux : typing___Optional[builtin___bool] = None,
        hide_adult_content_violence : typing___Optional[builtin___bool] = None,
        hide_adult_content_sex : typing___Optional[builtin___bool] = None,
        timestamp_updated : typing___Optional[builtin___int] = None,
        hide_store_broadcast : typing___Optional[builtin___bool] = None,
        review_score_preference : typing___Optional[type___EUserReviewScorePreferenceValue] = None,
        timestamp_content_descriptor_preferences_updated : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"hide_adult_content_sex",b"hide_adult_content_sex",u"hide_adult_content_violence",b"hide_adult_content_violence",u"hide_store_broadcast",b"hide_store_broadcast",u"platform_linux",b"platform_linux",u"platform_mac",b"platform_mac",u"platform_windows",b"platform_windows",u"primary_language",b"primary_language",u"review_score_preference",b"review_score_preference",u"secondary_languages",b"secondary_languages",u"timestamp_content_descriptor_preferences_updated",b"timestamp_content_descriptor_preferences_updated",u"timestamp_updated",b"timestamp_updated"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"hide_adult_content_sex",b"hide_adult_content_sex",u"hide_adult_content_violence",b"hide_adult_content_violence",u"hide_store_broadcast",b"hide_store_broadcast",u"platform_linux",b"platform_linux",u"platform_mac",b"platform_mac",u"platform_windows",b"platform_windows",u"primary_language",b"primary_language",u"review_score_preference",b"review_score_preference",u"secondary_languages",b"secondary_languages",u"timestamp_content_descriptor_preferences_updated",b"timestamp_content_descriptor_preferences_updated",u"timestamp_updated",b"timestamp_updated"]) -> None: ...
type___CStore_UserPreferences = CStore_UserPreferences

class CStore_UserTagPreferences(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Tag(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        tagid: builtin___int = ...
        name: typing___Text = ...
        timestamp_added: builtin___int = ...

        def __init__(self,
            *,
            tagid : typing___Optional[builtin___int] = None,
            name : typing___Optional[typing___Text] = None,
            timestamp_added : typing___Optional[builtin___int] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"name",b"name",u"tagid",b"tagid",u"timestamp_added",b"timestamp_added"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"tagid",b"tagid",u"timestamp_added",b"timestamp_added"]) -> None: ...
    type___Tag = Tag


    @property
    def tags_to_exclude(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___CStore_UserTagPreferences.Tag]: ...

    def __init__(self,
        *,
        tags_to_exclude : typing___Optional[typing___Iterable[type___CStore_UserTagPreferences.Tag]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"tags_to_exclude",b"tags_to_exclude"]) -> None: ...
type___CStore_UserTagPreferences = CStore_UserTagPreferences

class CStore_UserContentDescriptorPreferences(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class ContentDescriptor(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        content_descriptorid: builtin___int = ...
        timestamp_added: builtin___int = ...

        def __init__(self,
            *,
            content_descriptorid : typing___Optional[builtin___int] = None,
            timestamp_added : typing___Optional[builtin___int] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"content_descriptorid",b"content_descriptorid",u"timestamp_added",b"timestamp_added"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"content_descriptorid",b"content_descriptorid",u"timestamp_added",b"timestamp_added"]) -> None: ...
    type___ContentDescriptor = ContentDescriptor


    @property
    def content_descriptors_to_exclude(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___CStore_UserContentDescriptorPreferences.ContentDescriptor]: ...

    def __init__(self,
        *,
        content_descriptors_to_exclude : typing___Optional[typing___Iterable[type___CStore_UserContentDescriptorPreferences.ContentDescriptor]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"content_descriptors_to_exclude",b"content_descriptors_to_exclude"]) -> None: ...
type___CStore_UserContentDescriptorPreferences = CStore_UserContentDescriptorPreferences

class CStore_GetStorePreferences_Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def preferences(self) -> type___CStore_UserPreferences: ...

    @property
    def tag_preferences(self) -> type___CStore_UserTagPreferences: ...

    @property
    def content_descriptor_preferences(self) -> type___CStore_UserContentDescriptorPreferences: ...

    def __init__(self,
        *,
        preferences : typing___Optional[type___CStore_UserPreferences] = None,
        tag_preferences : typing___Optional[type___CStore_UserTagPreferences] = None,
        content_descriptor_preferences : typing___Optional[type___CStore_UserContentDescriptorPreferences] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"content_descriptor_preferences",b"content_descriptor_preferences",u"preferences",b"preferences",u"tag_preferences",b"tag_preferences"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"content_descriptor_preferences",b"content_descriptor_preferences",u"preferences",b"preferences",u"tag_preferences",b"tag_preferences"]) -> None: ...
type___CStore_GetStorePreferences_Response = CStore_GetStorePreferences_Response

class CStore_StorePreferencesChanged_Notification(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def preferences(self) -> type___CStore_UserPreferences: ...

    @property
    def tag_preferences(self) -> type___CStore_UserTagPreferences: ...

    @property
    def content_descriptor_preferences(self) -> type___CStore_UserContentDescriptorPreferences: ...

    def __init__(self,
        *,
        preferences : typing___Optional[type___CStore_UserPreferences] = None,
        tag_preferences : typing___Optional[type___CStore_UserTagPreferences] = None,
        content_descriptor_preferences : typing___Optional[type___CStore_UserContentDescriptorPreferences] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"content_descriptor_preferences",b"content_descriptor_preferences",u"preferences",b"preferences",u"tag_preferences",b"tag_preferences"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"content_descriptor_preferences",b"content_descriptor_preferences",u"preferences",b"preferences",u"tag_preferences",b"tag_preferences"]) -> None: ...
type___CStore_StorePreferencesChanged_Notification = CStore_StorePreferencesChanged_Notification

class Store(google___protobuf___service___Service, metaclass=abc___ABCMeta):
    @abc___abstractmethod
    def GetLocalizedNameForTags(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CStore_GetLocalizedNameForTags_Request,
        done: typing___Optional[typing___Callable[[type___CStore_GetLocalizedNameForTags_Response], None]],
    ) -> concurrent___futures___Future[type___CStore_GetLocalizedNameForTags_Response]: ...
    @abc___abstractmethod
    def GetStorePreferences(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CStore_GetStorePreferences_Request,
        done: typing___Optional[typing___Callable[[type___CStore_GetStorePreferences_Response], None]],
    ) -> concurrent___futures___Future[type___CStore_GetStorePreferences_Response]: ...
class Store_Stub(Store):
    def __init__(self, rpc_channel: google___protobuf___service___RpcChannel) -> None: ...
    def GetLocalizedNameForTags(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CStore_GetLocalizedNameForTags_Request,
        done: typing___Optional[typing___Callable[[type___CStore_GetLocalizedNameForTags_Response], None]],
    ) -> concurrent___futures___Future[type___CStore_GetLocalizedNameForTags_Response]: ...
    def GetStorePreferences(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CStore_GetStorePreferences_Request,
        done: typing___Optional[typing___Callable[[type___CStore_GetStorePreferences_Response], None]],
    ) -> concurrent___futures___Future[type___CStore_GetStorePreferences_Response]: ...
class StoreClient(google___protobuf___service___Service, metaclass=abc___ABCMeta):
    @abc___abstractmethod
    def NotifyStorePreferencesChanged(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CStore_StorePreferencesChanged_Notification,
        done: typing___Optional[typing___Callable[[steammessages_unified_base_pb2___NoResponse], None]],
    ) -> concurrent___futures___Future[steammessages_unified_base_pb2___NoResponse]: ...
class StoreClient_Stub(StoreClient):
    def __init__(self, rpc_channel: google___protobuf___service___RpcChannel) -> None: ...
    def NotifyStorePreferencesChanged(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CStore_StorePreferencesChanged_Notification,
        done: typing___Optional[typing___Callable[[steammessages_unified_base_pb2___NoResponse], None]],
    ) -> concurrent___futures___Future[steammessages_unified_base_pb2___NoResponse]: ...