# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from abc import (
    ABCMeta as abc___ABCMeta,
    abstractmethod as abc___abstractmethod,
)

from concurrent.futures import (
    Future as concurrent___futures___Future,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.service import (
    RpcChannel as google___protobuf___service___RpcChannel,
    RpcController as google___protobuf___service___RpcController,
    Service as google___protobuf___service___Service,
)

from steammessages_unified_base_pb2 import (
    NoResponse as steammessages_unified_base_pb2___NoResponse,
)

from typing import (
    Callable as typing___Callable,
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class ParentalApp(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    appid: builtin___int = ...
    is_allowed: builtin___bool = ...

    def __init__(self,
        *,
        appid : typing___Optional[builtin___int] = None,
        is_allowed : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"appid",b"appid",u"is_allowed",b"is_allowed"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"appid",b"appid",u"is_allowed",b"is_allowed"]) -> None: ...
type___ParentalApp = ParentalApp

class ParentalSettings(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    steamid: builtin___int = ...
    applist_base_id: builtin___int = ...
    applist_base_description: typing___Text = ...
    passwordhashtype: builtin___int = ...
    salt: builtin___bytes = ...
    passwordhash: builtin___bytes = ...
    is_enabled: builtin___bool = ...
    enabled_features: builtin___int = ...
    recovery_email: typing___Text = ...
    is_site_license_lock: builtin___bool = ...

    @property
    def applist_base(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ParentalApp]: ...

    @property
    def applist_custom(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ParentalApp]: ...

    def __init__(self,
        *,
        steamid : typing___Optional[builtin___int] = None,
        applist_base_id : typing___Optional[builtin___int] = None,
        applist_base_description : typing___Optional[typing___Text] = None,
        applist_base : typing___Optional[typing___Iterable[type___ParentalApp]] = None,
        applist_custom : typing___Optional[typing___Iterable[type___ParentalApp]] = None,
        passwordhashtype : typing___Optional[builtin___int] = None,
        salt : typing___Optional[builtin___bytes] = None,
        passwordhash : typing___Optional[builtin___bytes] = None,
        is_enabled : typing___Optional[builtin___bool] = None,
        enabled_features : typing___Optional[builtin___int] = None,
        recovery_email : typing___Optional[typing___Text] = None,
        is_site_license_lock : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"applist_base_description",b"applist_base_description",u"applist_base_id",b"applist_base_id",u"enabled_features",b"enabled_features",u"is_enabled",b"is_enabled",u"is_site_license_lock",b"is_site_license_lock",u"passwordhash",b"passwordhash",u"passwordhashtype",b"passwordhashtype",u"recovery_email",b"recovery_email",u"salt",b"salt",u"steamid",b"steamid"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"applist_base",b"applist_base",u"applist_base_description",b"applist_base_description",u"applist_base_id",b"applist_base_id",u"applist_custom",b"applist_custom",u"enabled_features",b"enabled_features",u"is_enabled",b"is_enabled",u"is_site_license_lock",b"is_site_license_lock",u"passwordhash",b"passwordhash",u"passwordhashtype",b"passwordhashtype",u"recovery_email",b"recovery_email",u"salt",b"salt",u"steamid",b"steamid"]) -> None: ...
type___ParentalSettings = ParentalSettings

class CParental_EnableParentalSettings_Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    password: typing___Text = ...
    sessionid: typing___Text = ...
    enablecode: builtin___int = ...
    steamid: builtin___int = ...

    @property
    def settings(self) -> type___ParentalSettings: ...

    def __init__(self,
        *,
        password : typing___Optional[typing___Text] = None,
        settings : typing___Optional[type___ParentalSettings] = None,
        sessionid : typing___Optional[typing___Text] = None,
        enablecode : typing___Optional[builtin___int] = None,
        steamid : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"enablecode",b"enablecode",u"password",b"password",u"sessionid",b"sessionid",u"settings",b"settings",u"steamid",b"steamid"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"enablecode",b"enablecode",u"password",b"password",u"sessionid",b"sessionid",u"settings",b"settings",u"steamid",b"steamid"]) -> None: ...
type___CParental_EnableParentalSettings_Request = CParental_EnableParentalSettings_Request

class CParental_EnableParentalSettings_Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___CParental_EnableParentalSettings_Response = CParental_EnableParentalSettings_Response

class CParental_DisableParentalSettings_Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    password: typing___Text = ...
    steamid: builtin___int = ...

    def __init__(self,
        *,
        password : typing___Optional[typing___Text] = None,
        steamid : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"password",b"password",u"steamid",b"steamid"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"password",b"password",u"steamid",b"steamid"]) -> None: ...
type___CParental_DisableParentalSettings_Request = CParental_DisableParentalSettings_Request

class CParental_DisableParentalSettings_Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___CParental_DisableParentalSettings_Response = CParental_DisableParentalSettings_Response

class CParental_GetParentalSettings_Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    steamid: builtin___int = ...

    def __init__(self,
        *,
        steamid : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"steamid",b"steamid"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"steamid",b"steamid"]) -> None: ...
type___CParental_GetParentalSettings_Request = CParental_GetParentalSettings_Request

class CParental_GetParentalSettings_Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def settings(self) -> type___ParentalSettings: ...

    def __init__(self,
        *,
        settings : typing___Optional[type___ParentalSettings] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"settings",b"settings"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"settings",b"settings"]) -> None: ...
type___CParental_GetParentalSettings_Response = CParental_GetParentalSettings_Response

class CParental_GetSignedParentalSettings_Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    priority: builtin___int = ...

    def __init__(self,
        *,
        priority : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"priority",b"priority"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"priority",b"priority"]) -> None: ...
type___CParental_GetSignedParentalSettings_Request = CParental_GetSignedParentalSettings_Request

class CParental_GetSignedParentalSettings_Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    serialized_settings: builtin___bytes = ...
    signature: builtin___bytes = ...

    def __init__(self,
        *,
        serialized_settings : typing___Optional[builtin___bytes] = None,
        signature : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"serialized_settings",b"serialized_settings",u"signature",b"signature"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"serialized_settings",b"serialized_settings",u"signature",b"signature"]) -> None: ...
type___CParental_GetSignedParentalSettings_Response = CParental_GetSignedParentalSettings_Response

class CParental_SetParentalSettings_Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    password: typing___Text = ...
    new_password: typing___Text = ...
    sessionid: typing___Text = ...
    steamid: builtin___int = ...

    @property
    def settings(self) -> type___ParentalSettings: ...

    def __init__(self,
        *,
        password : typing___Optional[typing___Text] = None,
        settings : typing___Optional[type___ParentalSettings] = None,
        new_password : typing___Optional[typing___Text] = None,
        sessionid : typing___Optional[typing___Text] = None,
        steamid : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"new_password",b"new_password",u"password",b"password",u"sessionid",b"sessionid",u"settings",b"settings",u"steamid",b"steamid"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"new_password",b"new_password",u"password",b"password",u"sessionid",b"sessionid",u"settings",b"settings",u"steamid",b"steamid"]) -> None: ...
type___CParental_SetParentalSettings_Request = CParental_SetParentalSettings_Request

class CParental_SetParentalSettings_Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___CParental_SetParentalSettings_Response = CParental_SetParentalSettings_Response

class CParental_ValidateToken_Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    unlock_token: typing___Text = ...

    def __init__(self,
        *,
        unlock_token : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"unlock_token",b"unlock_token"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"unlock_token",b"unlock_token"]) -> None: ...
type___CParental_ValidateToken_Request = CParental_ValidateToken_Request

class CParental_ValidateToken_Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___CParental_ValidateToken_Response = CParental_ValidateToken_Response

class CParental_ValidatePassword_Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    password: typing___Text = ...
    session: typing___Text = ...
    send_unlock_on_success: builtin___bool = ...

    def __init__(self,
        *,
        password : typing___Optional[typing___Text] = None,
        session : typing___Optional[typing___Text] = None,
        send_unlock_on_success : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"password",b"password",u"send_unlock_on_success",b"send_unlock_on_success",u"session",b"session"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"password",b"password",u"send_unlock_on_success",b"send_unlock_on_success",u"session",b"session"]) -> None: ...
type___CParental_ValidatePassword_Request = CParental_ValidatePassword_Request

class CParental_ValidatePassword_Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    token: typing___Text = ...

    def __init__(self,
        *,
        token : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"token",b"token"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"token",b"token"]) -> None: ...
type___CParental_ValidatePassword_Response = CParental_ValidatePassword_Response

class CParental_LockClient_Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    session: typing___Text = ...

    def __init__(self,
        *,
        session : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"session",b"session"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"session",b"session"]) -> None: ...
type___CParental_LockClient_Request = CParental_LockClient_Request

class CParental_LockClient_Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___CParental_LockClient_Response = CParental_LockClient_Response

class CParental_RequestRecoveryCode_Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___CParental_RequestRecoveryCode_Request = CParental_RequestRecoveryCode_Request

class CParental_RequestRecoveryCode_Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___CParental_RequestRecoveryCode_Response = CParental_RequestRecoveryCode_Response

class CParental_DisableWithRecoveryCode_Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    recovery_code: builtin___int = ...
    steamid: builtin___int = ...

    def __init__(self,
        *,
        recovery_code : typing___Optional[builtin___int] = None,
        steamid : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"recovery_code",b"recovery_code",u"steamid",b"steamid"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"recovery_code",b"recovery_code",u"steamid",b"steamid"]) -> None: ...
type___CParental_DisableWithRecoveryCode_Request = CParental_DisableWithRecoveryCode_Request

class CParental_DisableWithRecoveryCode_Response(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___CParental_DisableWithRecoveryCode_Response = CParental_DisableWithRecoveryCode_Response

class CParental_ParentalSettingsChange_Notification(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    serialized_settings: builtin___bytes = ...
    signature: builtin___bytes = ...
    password: typing___Text = ...
    sessionid: typing___Text = ...

    def __init__(self,
        *,
        serialized_settings : typing___Optional[builtin___bytes] = None,
        signature : typing___Optional[builtin___bytes] = None,
        password : typing___Optional[typing___Text] = None,
        sessionid : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"password",b"password",u"serialized_settings",b"serialized_settings",u"sessionid",b"sessionid",u"signature",b"signature"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"password",b"password",u"serialized_settings",b"serialized_settings",u"sessionid",b"sessionid",u"signature",b"signature"]) -> None: ...
type___CParental_ParentalSettingsChange_Notification = CParental_ParentalSettingsChange_Notification

class CParental_ParentalUnlock_Notification(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    password: typing___Text = ...
    sessionid: typing___Text = ...

    def __init__(self,
        *,
        password : typing___Optional[typing___Text] = None,
        sessionid : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"password",b"password",u"sessionid",b"sessionid"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"password",b"password",u"sessionid",b"sessionid"]) -> None: ...
type___CParental_ParentalUnlock_Notification = CParental_ParentalUnlock_Notification

class CParental_ParentalLock_Notification(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    sessionid: typing___Text = ...

    def __init__(self,
        *,
        sessionid : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"sessionid",b"sessionid"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"sessionid",b"sessionid"]) -> None: ...
type___CParental_ParentalLock_Notification = CParental_ParentalLock_Notification

class Parental(google___protobuf___service___Service, metaclass=abc___ABCMeta):
    @abc___abstractmethod
    def EnableParentalSettings(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_EnableParentalSettings_Request,
        done: typing___Optional[typing___Callable[[type___CParental_EnableParentalSettings_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_EnableParentalSettings_Response]: ...
    @abc___abstractmethod
    def DisableParentalSettings(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_DisableParentalSettings_Request,
        done: typing___Optional[typing___Callable[[type___CParental_DisableParentalSettings_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_DisableParentalSettings_Response]: ...
    @abc___abstractmethod
    def GetParentalSettings(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_GetParentalSettings_Request,
        done: typing___Optional[typing___Callable[[type___CParental_GetParentalSettings_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_GetParentalSettings_Response]: ...
    @abc___abstractmethod
    def GetSignedParentalSettings(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_GetSignedParentalSettings_Request,
        done: typing___Optional[typing___Callable[[type___CParental_GetSignedParentalSettings_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_GetSignedParentalSettings_Response]: ...
    @abc___abstractmethod
    def SetParentalSettings(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_SetParentalSettings_Request,
        done: typing___Optional[typing___Callable[[type___CParental_SetParentalSettings_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_SetParentalSettings_Response]: ...
    @abc___abstractmethod
    def ValidateToken(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_ValidateToken_Request,
        done: typing___Optional[typing___Callable[[type___CParental_ValidateToken_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_ValidateToken_Response]: ...
    @abc___abstractmethod
    def ValidatePassword(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_ValidatePassword_Request,
        done: typing___Optional[typing___Callable[[type___CParental_ValidatePassword_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_ValidatePassword_Response]: ...
    @abc___abstractmethod
    def LockClient(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_LockClient_Request,
        done: typing___Optional[typing___Callable[[type___CParental_LockClient_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_LockClient_Response]: ...
    @abc___abstractmethod
    def RequestRecoveryCode(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_RequestRecoveryCode_Request,
        done: typing___Optional[typing___Callable[[type___CParental_RequestRecoveryCode_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_RequestRecoveryCode_Response]: ...
    @abc___abstractmethod
    def DisableWithRecoveryCode(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_DisableWithRecoveryCode_Request,
        done: typing___Optional[typing___Callable[[type___CParental_DisableWithRecoveryCode_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_DisableWithRecoveryCode_Response]: ...
class Parental_Stub(Parental):
    def __init__(self, rpc_channel: google___protobuf___service___RpcChannel) -> None: ...
    def EnableParentalSettings(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_EnableParentalSettings_Request,
        done: typing___Optional[typing___Callable[[type___CParental_EnableParentalSettings_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_EnableParentalSettings_Response]: ...
    def DisableParentalSettings(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_DisableParentalSettings_Request,
        done: typing___Optional[typing___Callable[[type___CParental_DisableParentalSettings_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_DisableParentalSettings_Response]: ...
    def GetParentalSettings(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_GetParentalSettings_Request,
        done: typing___Optional[typing___Callable[[type___CParental_GetParentalSettings_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_GetParentalSettings_Response]: ...
    def GetSignedParentalSettings(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_GetSignedParentalSettings_Request,
        done: typing___Optional[typing___Callable[[type___CParental_GetSignedParentalSettings_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_GetSignedParentalSettings_Response]: ...
    def SetParentalSettings(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_SetParentalSettings_Request,
        done: typing___Optional[typing___Callable[[type___CParental_SetParentalSettings_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_SetParentalSettings_Response]: ...
    def ValidateToken(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_ValidateToken_Request,
        done: typing___Optional[typing___Callable[[type___CParental_ValidateToken_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_ValidateToken_Response]: ...
    def ValidatePassword(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_ValidatePassword_Request,
        done: typing___Optional[typing___Callable[[type___CParental_ValidatePassword_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_ValidatePassword_Response]: ...
    def LockClient(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_LockClient_Request,
        done: typing___Optional[typing___Callable[[type___CParental_LockClient_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_LockClient_Response]: ...
    def RequestRecoveryCode(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_RequestRecoveryCode_Request,
        done: typing___Optional[typing___Callable[[type___CParental_RequestRecoveryCode_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_RequestRecoveryCode_Response]: ...
    def DisableWithRecoveryCode(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_DisableWithRecoveryCode_Request,
        done: typing___Optional[typing___Callable[[type___CParental_DisableWithRecoveryCode_Response], None]],
    ) -> concurrent___futures___Future[type___CParental_DisableWithRecoveryCode_Response]: ...
class ParentalClient(google___protobuf___service___Service, metaclass=abc___ABCMeta):
    @abc___abstractmethod
    def NotifySettingsChange(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_ParentalSettingsChange_Notification,
        done: typing___Optional[typing___Callable[[steammessages_unified_base_pb2___NoResponse], None]],
    ) -> concurrent___futures___Future[steammessages_unified_base_pb2___NoResponse]: ...
    @abc___abstractmethod
    def NotifyUnlock(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_ParentalUnlock_Notification,
        done: typing___Optional[typing___Callable[[steammessages_unified_base_pb2___NoResponse], None]],
    ) -> concurrent___futures___Future[steammessages_unified_base_pb2___NoResponse]: ...
    @abc___abstractmethod
    def NotifyLock(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_ParentalLock_Notification,
        done: typing___Optional[typing___Callable[[steammessages_unified_base_pb2___NoResponse], None]],
    ) -> concurrent___futures___Future[steammessages_unified_base_pb2___NoResponse]: ...
class ParentalClient_Stub(ParentalClient):
    def __init__(self, rpc_channel: google___protobuf___service___RpcChannel) -> None: ...
    def NotifySettingsChange(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_ParentalSettingsChange_Notification,
        done: typing___Optional[typing___Callable[[steammessages_unified_base_pb2___NoResponse], None]],
    ) -> concurrent___futures___Future[steammessages_unified_base_pb2___NoResponse]: ...
    def NotifyUnlock(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_ParentalUnlock_Notification,
        done: typing___Optional[typing___Callable[[steammessages_unified_base_pb2___NoResponse], None]],
    ) -> concurrent___futures___Future[steammessages_unified_base_pb2___NoResponse]: ...
    def NotifyLock(self,
        rpc_controller: google___protobuf___service___RpcController,
        request: type___CParental_ParentalLock_Notification,
        done: typing___Optional[typing___Callable[[steammessages_unified_base_pb2___NoResponse], None]],
    ) -> concurrent___futures___Future[steammessages_unified_base_pb2___NoResponse]: ...